const colors = {
  light: {
    text: "#1a1a1a",
    tint: "#E3000F",
    background: "#f6f6f8",
    foreground: "#1a1a1a",
    card: "#ffffff",
    cardForeground: "#1a1a1a",
    primary: "#E3000F",
    primaryForeground: "#ffffff",
    secondary: "#f0f0f3",
    secondaryForeground: "#1a1a1a",
    muted: "#f0f0f3",
    mutedForeground: "#8a8a8e",
    accent: "#E3000F",
    accentForeground: "#ffffff",
    destructive: "#E3000F",
    destructiveForeground: "#ffffff",
    border: "#e2e2e7",
    input: "#e2e2e7",
    success: "#22c55e",
    warning: "#f59e0b",
    info: "#3b82f6",
  },
  dark: {
    text: "#f5f5f5",
    tint: "#ff3b3b",
    background: "#111111",
    foreground: "#f5f5f5",
    card: "#1e1e1e",
    cardForeground: "#f5f5f5",
    primary: "#ff3b3b",
    primaryForeground: "#ffffff",
    secondary: "#2a2a2a",
    secondaryForeground: "#f5f5f5",
    muted: "#2a2a2a",
    mutedForeground: "#8a8a8e",
    accent: "#ff3b3b",
    accentForeground: "#ffffff",
    destructive: "#ff3b3b",
    destructiveForeground: "#ffffff",
    border: "#2e2e2e",
    input: "#2e2e2e",
    success: "#22c55e",
    warning: "#f59e0b",
    info: "#3b82f6",
  },
  radius: 10,
};

export default colors;
