"use client";

import { useEffect, useMemo, useState } from "react";
import type { FormEvent, ReactNode } from "react";
import type { CalendarSource, CommitteeMembership, FraktionCase, FraktionCommittee, FraktionDocument, FraktionEvent, FraktionMember, FraktionProfile, FraktionTask, PortalData } from "@/lib/types";

type View = "dashboard" | "termine" | "aufgaben" | "vorgaenge" | "ausschuesse" | "profile" | "mitglieder" | "dokumente" | "sync";

const nav: Array<{ id: View; icon: string; label: string }> = [
  { id: "dashboard", icon: "Ü", label: "Cockpit" },
  { id: "termine", icon: "T", label: "Termine" },
  { id: "aufgaben", icon: "A", label: "Aufgaben" },
  { id: "vorgaenge", icon: "V", label: "Vorgänge" },
  { id: "ausschuesse", icon: "G", label: "Ausschüsse" },
  { id: "profile", icon: "P", label: "Profile" },
  { id: "mitglieder", icon: "F", label: "Fraktion" },
  { id: "dokumente", icon: "D", label: "Dokumente" },
  { id: "sync", icon: "K", label: "Kalender" }
];

const categories = ["Stadtrat", "Ausschuss", "Ortsbeirat", "Fraktionssitzung", "Partei", "Veranstaltung", "Sonstiges"];
const taskStatus = ["offen", "in_bearbeitung", "wartend", "pruefung", "erledigt", "verworfen"];
const priorities = ["niedrig", "normal", "hoch", "kritisch"];
const prepStatus = ["offen", "unterlagen_fehlen", "vorbereiten", "rueckfrage", "vorbereitet", "erledigt"];

const profileImageBySlug: Record<string, string> = {
  "patrick-schaefer": "/profile-images/IMG_0078.jpeg",
  "janina-eispert": "/profile-images/IMG_0079.jpeg",
  "harald-brandstaedter": "/profile-images/IMG_0080.jpeg",
  "andreas-rahm": "/profile-images/IMG_0081.jpeg",
  "raymond-germany": "/profile-images/IMG_0082.jpeg",
  "michael-krauss": "/profile-images/IMG_0083.jpeg",
  "anna-raab": "/profile-images/IMG_0084.jpeg",
  "heike-spies": "/profile-images/IMG_0085.jpeg",
  "petra-janson-peermann": "/profile-images/IMG_0086.jpeg",
  "moritz-behncke": "/profile-images/IMG_0087.jpeg",
  "joerg-harz": "/profile-images/IMG_0088.jpeg",
  "marcel-schulz": "/profile-images/IMG_0090.jpeg"
};

const avatarImgStyle = { width: "100%", height: "100%", objectFit: "cover", borderRadius: "inherit", display: "block" } as const;

function slugifyName(input: string) {
  return input.toLowerCase().replace(/ß/g, "ss").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}
function dateTime(value: string | null | undefined) { if (!value) return "ohne Datum"; return new Intl.DateTimeFormat("de-DE", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
function dateOnly(value: string | null | undefined) { if (!value) return "ohne Datum"; return new Intl.DateTimeFormat("de-DE", { dateStyle: "medium" }).format(new Date(value)); }
async function postRecord(table: string, payload: Record<string, unknown>) { const response = await fetch("/api/records", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ table, payload }) }); const json = await response.json(); if (!response.ok) throw new Error(json.error || "Speichern fehlgeschlagen"); return json; }
async function patchRecord(table: string, id: string, payload: Record<string, unknown>) { const response = await fetch("/api/records", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ table, id, payload }) }); const json = await response.json(); if (!response.ok) throw new Error(json.error || "Aktualisieren fehlgeschlagen"); return json; }
function classNames(...items: Array<string | false | null | undefined>) { return items.filter(Boolean).join(" "); }
function Stat({ label, value, hint }: { label: string; value: string | number; hint: string }) { return <div className="surface stat"><div className="muted small">{label}</div><div className="metric">{value}</div><div className="small muted">{hint}</div></div>; }
function Badge({ children, tone = "" }: { children: ReactNode; tone?: "" | "red" | "green" | "blue" | "gold" }) { return <span className={`badge ${tone}`}>{children}</span>; }

export default function Home() {
  const [view, setView] = useState<View>("dashboard");
  const [data, setData] = useState<PortalData | null>(null);
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState<string | null>(null);
  const [currentProfile, setCurrentProfile] = useState<FraktionProfile | null>(null);
  const [menuOpen, setMenuOpen] = useState(false);

  async function load() { setLoading(true); const response = await fetch("/api/data", { cache: "no-store" }); const json = await response.json(); setData(json); setLoading(false); }
  useEffect(() => { load(); }, []);
  useEffect(() => { if (!data) return; const saved = window.localStorage.getItem("fraktion-profile-slug"); if (!saved) return; const profile = data.profiles.find(item => item.slug === saved); if (profile) setCurrentProfile(profile); }, [data]);

  const profiles = data?.profiles ?? [];
  const cases = data?.cases ?? [];
  const committees = data?.committees ?? [];
  const memberships = data?.committee_memberships ?? [];
  const events = data?.events ?? [];
  const tasks = data?.tasks ?? [];
  const members = data?.members ?? [];
  const documents = data?.documents ?? [];
  const sources = data?.calendar_sources ?? [];

  const upcoming = useMemo(() => events.filter(e => new Date(e.starts_at).getTime() >= Date.now() - 86400000).slice(0, 10), [events]);
  const prepEvents = useMemo(() => upcoming.filter(e => e.requires_preparation !== false && (e.preparation_status ?? "offen") !== "erledigt"), [upcoming]);
  const openTasks = useMemo(() => tasks.filter(t => t.status !== "erledigt" && t.status !== "verworfen"), [tasks]);
  const myTasks = useMemo(() => openTasks.filter(t => !currentProfile || !t.assignee || t.assignee.includes(currentProfile.display_name) || t.assignee.includes(currentProfile.full_name)), [openTasks, currentProfile]);
  const activeCases = useMemo(() => cases.filter(c => c.status !== "erledigt" && c.status !== "archiv"), [cases]);

  function activateView(nextView: View) { setView(nextView); setMenuOpen(false); }
  async function handleLogin(profileSlug: string, code: string) { const response = await fetch("/api/auth/session", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ profileSlug, code }) }); const json = await response.json(); if (!response.ok) { setMessage(json.error || "Login fehlgeschlagen."); return; } setCurrentProfile(json.profile); window.localStorage.setItem("fraktion-profile-slug", json.profile.slug); setMessage(json.prototypeMode ? "Profil aktiv. Hinweis: Der Login läuft im Prototyp-Modus, bis PORTAL_SHARED_CODE gesetzt ist." : "Login erfolgreich."); }
  function logout() { window.localStorage.removeItem("fraktion-profile-slug"); setCurrentProfile(null); setMenuOpen(false); }
  async function handleEventSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const starts = String(form.get("date")) + "T" + String(form.get("time") || "15:00") + ":00+02:00"; await postRecord("events", { title: form.get("title"), starts_at: starts, ends_at: null, all_day: false, location: form.get("location"), description: form.get("description"), category: form.get("category"), meeting_body: form.get("meeting_body"), preparation_status: form.get("preparation_status") || "offen", requires_preparation: true, source: "manual", owner: currentProfile?.full_name ?? "Fraktion", relevance: form.get("relevance") || "offen", status: "scheduled" }); event.currentTarget.reset(); setMessage("Termin gespeichert."); await load(); }
  async function handleTaskSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await postRecord("tasks", { title: form.get("title"), description: form.get("description"), assignee: form.get("assignee") || currentProfile?.full_name, due_date: form.get("due_date") || null, status: "offen", priority: form.get("priority") || "normal", event_id: null, case_id: form.get("case_id") || null }); event.currentTarget.reset(); setMessage("Aufgabe erstellt."); await load(); }
  async function handleCaseSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const title = String(form.get("title")); await postRecord("cases", { title, slug: title.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""), description: form.get("description"), owner: form.get("owner") || currentProfile?.full_name, status: "offen", priority: form.get("priority") || "normal", next_step: form.get("next_step"), tags: [] }); event.currentTarget.reset(); setMessage("Vorgang angelegt."); await load(); }
  async function handleSourceSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await postRecord("calendar_sources", { name: form.get("name"), type: "apple_ics", url: form.get("url"), owner: form.get("owner") || currentProfile?.full_name || "Patrick", enabled: true, notes: form.get("notes") }); event.currentTarget.reset(); setMessage("Kalenderquelle hinterlegt. Der Sync-Endpunkt ist vorbereitet."); await load(); }
  async function updateTaskStatus(task: FraktionTask, status: string) { await patchRecord("tasks", task.id, { status }); await load(); }
  async function updateEventPrep(event: FraktionEvent, preparation_status: string) { await patchRecord("events", event.id, { preparation_status }); await load(); }

  if (!data || loading) return <main className="login-shell"><div className="login-card surface"><Brand /><div className="pulse" /><p className="muted">Fraktionscockpit wird geladen…</p></div></main>;
  if (!currentProfile) return <LoginScreen profiles={profiles} message={message} onLogin={handleLogin} />;

  return <main className={classNames("app-shell", menuOpen && "menu-open")}><MobileHeader onToggle={() => setMenuOpen(value => !value)} open={menuOpen} />{menuOpen && <button className="mobile-scrim" aria-label="Menü schließen" onClick={() => setMenuOpen(false)} />}<aside className={classNames("sidebar", menuOpen && "open")}><Brand /><div className="active-profile compact-profile"><Avatar profile={currentProfile} /><div><strong>{currentProfile.full_name}</strong><span>{currentProfile.role}</span></div></div><nav className="nav" aria-label="Hauptnavigation">{nav.map(item => <button key={item.id} className={view === item.id ? "active" : ""} onClick={() => activateView(item.id)}><span>{item.icon}</span>{item.label}</button>)}</nav><button className="logout" onClick={logout}>Profil wechseln</button></aside><section className="main"><div className="hero surface"><div><div className="eyebrow">SPD-Fraktion Kaiserslautern · Intern</div><h1>Hallo, {currentProfile.display_name}.</h1><p>Fraktionsbetriebssystem für RIS-Termine, Vorbereitung, Vorgänge, Ausschüsse, Aufgaben und Dokumente.</p></div><div className="hero-profile"><Avatar profile={currentProfile} large /><div><strong>{currentProfile.role}</strong><span>{currentProfile.portal_role.replace("_", " ")}</span></div></div></div>{message && <div className="notice surface">{message}</div>}{data.error && <div className="notice surface">Supabase-Hinweis: {data.error}</div>}
  <section className={classNames("section", view === "dashboard" && "active")}><div className="grid cols-4"><Stat label="Vorbereitung" value={prepEvents.length} hint="Termine brauchen Bearbeitung" /><Stat label="Vorgänge" value={activeCases.length} hint="aktive Themenakten" /><Stat label="Ausschüsse" value={committees.length} hint="bisher erfasst" /><Stat label="Meine Aufgaben" value={myTasks.length} hint="gefiltert nach Profil" /></div><div className="grid cols-2 spacious"><div className="surface card"><SectionTitle title="Vorbereitung nötig" subtitle="RIS-/Fraktionstermine mit offenem Status" /><EventList events={prepEvents.slice(0, 5)} onPrep={updateEventPrep} /></div><div className="surface card"><SectionTitle title="Aktive Vorgänge" subtitle="Themenakten mit nächstem Schritt" /><CaseList cases={activeCases.slice(0, 6)} /></div></div></section>
  <section className={classNames("section", view === "termine" && "active")}><div className="grid cols-2"><div className="surface card"><SectionTitle title="Neuen Termin anlegen" subtitle="Mit Vorbereitung und Gremium" /><form className="form-grid" onSubmit={handleEventSubmit}><input className="input wide" name="title" placeholder="Titel, z. B. Stadtrat" required /><input className="input" name="date" type="date" required /><input className="input" name="time" type="time" defaultValue="15:00" /><select className="select" name="category">{categories.map(c => <option key={c}>{c}</option>)}</select><select className="select" name="relevance"><option value="offen">Relevanz offen</option><option value="beide">für beide</option><option value="patrick">Patrick</option><option value="luca">Luca</option><option value="nicht_relevant">nicht relevant</option></select><input className="input wide" name="meeting_body" placeholder="Gremium, z. B. Bauausschuss" /><select className="select wide" name="preparation_status">{prepStatus.map(s => <option key={s} value={s}>{s.replaceAll("_", " ")}</option>)}</select><input className="input wide" name="location" placeholder="Ort" /><textarea className="textarea wide" name="description" placeholder="Beschreibung / Notiz" /><button className="btn red wide">Termin speichern</button></form></div><div className="surface card"><SectionTitle title="Terminzentrum" subtitle="Chronologisch aus Supabase / RIS-Import" /><EventList events={events} onPrep={updateEventPrep} /></div></div></section>
  <section className={classNames("section", view === "aufgaben" && "active")}><div className="grid cols-2"><div className="surface card"><SectionTitle title="Neue Aufgabe" subtitle="Mit Vorgang verknüpfen" /><form className="form-grid" onSubmit={handleTaskSubmit}><input className="input wide" name="title" placeholder="Aufgabe" required /><input className="input" name="assignee" placeholder="Zuständig" defaultValue={currentProfile.full_name} /><input className="input" name="due_date" type="date" /><select className="select" name="priority">{priorities.map(p => <option key={p}>{p}</option>)}</select><select className="select" name="case_id"><option value="">kein Vorgang</option>{cases.map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select><textarea className="textarea wide" name="description" placeholder="Beschreibung" /><button className="btn red wide">Aufgabe erstellen</button></form></div><div className="surface card"><SectionTitle title="Aufgaben-Board" subtitle="Alle offenen Arbeitsstände" /><TaskList tasks={tasks} onStatus={updateTaskStatus} /></div></div></section>
  <section className={classNames("section", view === "vorgaenge" && "active")}><div className="grid cols-2"><div className="surface card"><SectionTitle title="Neuen Vorgang anlegen" subtitle="Themenakte für Antrag, Anfrage oder Sachstand" /><form className="form-grid" onSubmit={handleCaseSubmit}><input className="input wide" name="title" placeholder="Titel des Vorgangs" required /><input className="input" name="owner" placeholder="Zuständig" defaultValue={currentProfile.full_name} /><select className="select" name="priority">{priorities.map(p => <option key={p}>{p}</option>)}</select><input className="input wide" name="next_step" placeholder="Nächster Schritt" /><textarea className="textarea wide" name="description" placeholder="Kurzbeschreibung" /><button className="btn red wide">Vorgang anlegen</button></form></div><div className="surface card"><SectionTitle title="Vorgänge / Themenakten" subtitle="Status, Zuständigkeit und nächster Schritt" /><CaseList cases={cases} /></div></div></section>
  <section className={classNames("section", view === "ausschuesse" && "active")}><SectionTitle title="Ausschüsse und Vertretungen" subtitle="Aus den hochgeladenen Anwesenheitslisten" /><CommitteeList committees={committees} memberships={memberships} /></section><section className={classNames("section", view === "profile" && "active")}><SectionTitle title="Nutzerprofile" subtitle="Arbeitsprofile mit Ausschusskontext" /><div className="profile-grid">{profiles.map(profile => <ProfileCard key={profile.slug} profile={profile} active={profile.slug === currentProfile.slug} memberships={memberships} committees={committees} />)}</div></section><section className={classNames("section", view === "mitglieder" && "active")}><SectionTitle title="Fraktionsmitglieder" subtitle="Ratsmitglieder und bekannte Ausschusszuordnungen" /><div className="profile-grid">{members.map(member => <MemberCard key={member.id} member={member} memberships={memberships} committees={committees} />)}</div></section><section className={classNames("section", view === "dokumente" && "active")}><div className="surface card"><SectionTitle title="Dokumente" subtitle="Vorlagen, Anträge, Arbeitsstände und Themenakten" /><DocumentList documents={documents} cases={cases} /></div></section><section className={classNames("section", view === "sync" && "active")}><div className="grid cols-2"><div className="surface card"><SectionTitle title="Kalender & RIS" subtitle="Apple/ICS und öffentlicher Sitzungskalender" /><p className="muted">Der Sitzungskalender 2026 ist als feste Quelle vorbereitet. Zusätzlich kann der öffentliche RIS-Kalender später weiter synchronisiert werden.</p><form className="form-grid" onSubmit={handleSourceSubmit}><input className="input" name="name" placeholder="Name der Quelle" defaultValue="Patrick Apple Kalender" required /><input className="input" name="owner" placeholder="Eigentümer" defaultValue="Patrick Schäfer" /><input className="input wide" name="url" placeholder="https://...ics" required /><textarea className="textarea wide" name="notes" placeholder="Notiz, z. B. nur Fraktionskalender" /><button className="btn red wide">Kalenderquelle speichern</button></form><div className="footer-actions"><a className="btn light" href="/api/calendar/ics">Fraktionskalender abonnieren</a><a className="btn ghost" href="/api/data">API prüfen</a></div></div><div className="surface card"><SectionTitle title="Quellen" subtitle="Synchronisationsstatus" /><SourceList sources={sources} /></div></div></section></section></main>;
}

function Brand() { return <div className="brand"><img src="/FraktionslogoNeu.svg" alt="SPD-Fraktion Kaiserslautern" /></div>; }
function MobileHeader({ open, onToggle }: { open: boolean; onToggle: () => void }) { return <header className="mobile-header"><Brand /><button className="hamburger" aria-label={open ? "Menü schließen" : "Menü öffnen"} aria-expanded={open} onClick={onToggle}><span /><span /><span /></button></header>; }
function LoginScreen({ profiles, message, onLogin }: { profiles: FraktionProfile[]; message: string | null; onLogin: (profileSlug: string, code: string) => Promise<void> }) { const [selected, setSelected] = useState(profiles[0]?.slug ?? "luca-hoffmann"); const [code, setCode] = useState(""); const active = profiles.find(profile => profile.slug === selected) ?? profiles[0]; return <main className="login-shell"><div className="login-card surface"><Brand /><div className="login-hero"><div><div className="eyebrow">Profilzugang</div><h1>Fraktionscockpit</h1><p>Wähle dein Profil und melde dich für Termine, Aufgaben und Dokumente an.</p></div>{active && <Avatar profile={active} large />}</div>{message && <div className="notice">{message}</div>}<div className="profile-picker">{profiles.map(profile => <button key={profile.slug} className={selected === profile.slug ? "selected" : ""} onClick={() => setSelected(profile.slug)}><Avatar profile={profile} /><span>{profile.full_name}</span><small>{profile.role}</small></button>)}</div><form className="login-form" onSubmit={(event) => { event.preventDefault(); onLogin(selected, code); }}><input className="input" type="password" value={code} onChange={event => setCode(event.target.value)} placeholder="Zugangscode, falls aktiviert" /><button className="btn red">Einloggen</button></form><p className="muted small">Prototyp: Ohne gesetzten PORTAL_SHARED_CODE reicht die Profilauswahl. Für produktive Nutzung bitte Supabase Auth/Magic Links aktivieren.</p></div></main>; }
function Avatar({ profile, large = false }: { profile: FraktionProfile; large?: boolean }) { const image = profileImageBySlug[profile.slug]; return <div className={classNames("avatar", large && "large", profile.accent ?? "")}>{image ? <img src={image} alt={profile.full_name} style={avatarImgStyle} /> : profile.avatar_initials}</div>; }
function SectionTitle({ title, subtitle }: { title: string; subtitle: string }) { return <div className="section-title"><div><h2>{title}</h2><p>{subtitle}</p></div></div>; }
function CaseList({ cases }: { cases: FraktionCase[] }) { if (!cases.length) return <p className="muted">Noch keine Vorgänge.</p>; return <div className="list">{cases.map(c => <div className="item" key={c.id}><div className="item-head"><h3>{c.title}</h3><div className="badges"><Badge tone={c.priority === "hoch" || c.priority === "kritisch" ? "red" : "blue"}>{c.priority}</Badge><Badge>{c.status}</Badge></div></div>{c.description && <div className="small">{c.description}</div>}<div className="muted small">Zuständig: {c.owner || "offen"} · nächster Schritt: {c.next_step || "noch nicht gesetzt"}</div><div className="badges">{(c.tags ?? []).map(tag => <Badge key={tag}>{tag}</Badge>)}</div></div>)}</div>; }
function CommitteeList({ committees, memberships }: { committees: FraktionCommittee[]; memberships: CommitteeMembership[] }) { if (!committees.length) return <p className="muted">Noch keine Ausschüsse.</p>; return <div className="profile-grid">{committees.map(c => { const rows = memberships.filter(m => m.committee_slug === c.slug); return <div className="surface profile-card" key={c.slug}><div className="item-head"><h3>{c.title}</h3><Badge tone="red">{c.short_ref}</Badge></div><p className="muted small">{c.notes}</p><strong>Ordentliche Mitglieder</strong>{rows.filter(r => r.role === "member").map(r => <div className="small" key={r.id}>• {r.person_name}</div>)}<strong>Stellvertretende Mitglieder</strong>{rows.filter(r => r.role === "substitute").map(r => <div className="small" key={r.id}>• {r.person_name}</div>)}</div>; })}</div>; }
function committeeLabels(name: string, memberships: CommitteeMembership[], committees: FraktionCommittee[]) { return memberships.filter(m => m.person_name === name).map(m => `${committees.find(c => c.slug === m.committee_slug)?.short_ref ?? m.committee_slug} ${m.role === "substitute" ? "stv." : "ord."}`); }
function ProfileCard({ profile, active, memberships, committees }: { profile: FraktionProfile; active?: boolean; memberships: CommitteeMembership[]; committees: FraktionCommittee[] }) { const labels = committeeLabels(profile.full_name, memberships, committees); return <div className={classNames("surface", "profile-card", active && "is-active")}><div className="profile-top"><Avatar profile={profile} large /><div><h3>{profile.full_name}</h3><p>{profile.role}</p></div></div><div className="badges"><Badge tone={profile.is_staff ? "gold" : "red"}>{profile.is_staff ? "Sekretariat" : "Ratsmitglied"}</Badge>{profile.board_role && <Badge tone="blue">{profile.board_role}</Badge>}</div>{profile.bio && <p className="muted">{profile.bio}</p>}<div className="permission-row">{labels.length ? labels.map(label => <span key={label}>{label}</span>) : (profile.permissions ?? []).map(permission => <span key={permission}>{permission}</span>)}</div></div>; }
function EventList({ events, onPrep }: { events: FraktionEvent[]; onPrep?: (event: FraktionEvent, status: string) => Promise<void> }) { if (!events.length) return <p className="muted">Noch keine Termine.</p>; return <div className="list">{events.map(e => <div className="item" key={e.id}><div className="item-head"><h3>{e.title}</h3><div className="badges"><Badge tone="red">{e.category ?? "Termin"}</Badge><Badge tone="blue">{e.relevance ?? "offen"}</Badge></div></div><div className="muted small">{dateTime(e.starts_at)}{e.location ? ` · ${e.location}` : ""}</div><div className="small">Gremium: {e.meeting_body || e.title} · Vorbereitung: {e.preparation_status || "offen"}</div>{e.description && <div className="small">{e.description}</div>}{onPrep && <div className="toolbar">{prepStatus.map(s => <button className={(e.preparation_status ?? "offen") === s ? "btn red" : "btn light"} key={s} onClick={() => onPrep(e, s)}>{s.replaceAll("_", " ")}</button>)}</div>}</div>)}</div>; }
function TaskList({ tasks, onStatus }: { tasks: FraktionTask[]; onStatus: (task: FraktionTask, status: string) => Promise<void> }) { if (!tasks.length) return <p className="muted">Keine Aufgaben vorhanden.</p>; return <div className="list">{tasks.map(t => <div className="item" key={t.id}><div className="item-head"><h3>{t.title}</h3><Badge tone={t.priority === "hoch" || t.priority === "kritisch" ? "red" : ""}>{t.priority}</Badge></div><div className="muted small">{t.assignee || "nicht zugewiesen"} · fällig: {dateOnly(t.due_date)}</div>{t.description && <div className="small">{t.description}</div>}<div className="toolbar">{taskStatus.map(s => <button className={t.status === s ? "btn red" : "btn light"} key={s} onClick={() => onStatus(t, s)}>{s.replace("_", " ")}</button>)}</div></div>)}</div>; }
function MemberCard({ member, memberships, committees }: { member: FraktionMember; memberships: CommitteeMembership[]; committees: FraktionCommittee[] }) { const initials = member.name.split(" ").map(part => part[0]).join("").slice(0, 2); const labels = committeeLabels(member.name, memberships, committees); const image = profileImageBySlug[slugifyName(member.name)]; return <div className="surface profile-card"><div className="profile-top"><div className="avatar">{image ? <img src={image} alt={member.name} style={avatarImgStyle} /> : initials}</div><div><h3>{member.name}</h3><p>{member.role ?? "Fraktionsmitglied"}</p></div></div><p className="muted small">{labels.length ? labels.join(" · ") : member.committees ?? "Ausschüsse / Zuständigkeiten können ergänzt werden"}</p>{member.email && <p className="small">{member.email}</p>}</div>; }
function DocumentList({ documents, cases }: { documents: FraktionDocument[]; cases: FraktionCase[] }) { if (!documents.length) return <p className="muted">Noch keine Dokumente.</p>; return <div className="list">{documents.map(d => <div className="item" key={d.id}><div className="item-head"><h3>{d.title}</h3><Badge>{d.kind ?? d.category ?? "Dokument"}</Badge></div>{d.description && <div className="small">{d.description}</div>}<div className="muted small">Status: {d.status ?? "offen"} · Vorgang: {cases.find(c => c.id === d.case_id)?.title ?? "nicht verknüpft"}</div>{d.url && <a className="btn light" href={d.url} target="_blank">Öffnen</a>}</div>)}</div>; }
function SourceList({ sources }: { sources: CalendarSource[] }) { if (!sources.length) return <p className="muted">Noch keine Kalenderquellen.</p>; return <div className="list">{sources.map(s => <div className="item" key={s.id}><div className="item-head"><h3>{s.name}</h3><Badge tone={s.enabled ? "green" : ""}>{s.enabled ? "aktiv" : "inaktiv"}</Badge></div><div className="muted small">{s.owner} · {s.type} · letzter Sync: {s.last_synced_at ? dateTime(s.last_synced_at) : "noch nie"}</div>{s.notes && <div className="small">{s.notes}</div>}</div>)}</div>; }
