import type { FraktionEvent } from "./types";

export const sitzungskalender2026: FraktionEvent[] = [
  { id: "sk-2026-06-15-stadtrat", title: "Stadtrat", starts_at: "2026-06-15T15:00:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Stadtrat", source: "sitzungskalender_2026", source_uid: "sk-2026-06-15-stadtrat", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Stadtrat", preparation_status: "offen", requires_preparation: true, decision_needed: true },
  { id: "sk-2026-06-16-hospitalausschuss", title: "Hospitalausschuss", starts_at: "2026-06-16T16:30:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Ausschuss", source: "sitzungskalender_2026", source_uid: "sk-2026-06-16-hospitalausschuss", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Hospitalausschuss", preparation_status: "offen", requires_preparation: true, decision_needed: true },
  { id: "sk-2026-06-16-ortsbeirat-erlenbach", title: "Ortsbeirat Erlenbach", starts_at: "2026-06-16T19:00:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Ortsbeirat", source: "sitzungskalender_2026", source_uid: "sk-2026-06-16-ortsbeirat-erlenbach", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Ortsbeirat Erlenbach", preparation_status: "offen", requires_preparation: true, decision_needed: false },
  { id: "sk-2026-06-18-seniorenbeirat", title: "Seniorenbeirat", starts_at: "2026-06-18T14:00:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Beirat", source: "sitzungskalender_2026", source_uid: "sk-2026-06-18-seniorenbeirat", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Seniorenbeirat", preparation_status: "offen", requires_preparation: true, decision_needed: false },
  { id: "sk-2026-06-18-bauausschuss", title: "Bauausschuss", starts_at: "2026-06-18T15:00:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Ausschuss", source: "sitzungskalender_2026", source_uid: "sk-2026-06-18-bauausschuss", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Bauausschuss", preparation_status: "offen", requires_preparation: true, decision_needed: true },
  { id: "sk-2026-06-25-marktausschuss", title: "Marktausschuss", starts_at: "2026-06-25T16:00:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Ausschuss", source: "sitzungskalender_2026", source_uid: "sk-2026-06-25-marktausschuss", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Marktausschuss", preparation_status: "offen", requires_preparation: true, decision_needed: true },
  { id: "sk-2026-06-25-inklusionsbeirat", title: "Inklusionsbeirat", starts_at: "2026-06-25T17:00:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Beirat", source: "sitzungskalender_2026", source_uid: "sk-2026-06-25-inklusionsbeirat", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Inklusionsbeirat", preparation_status: "offen", requires_preparation: true, decision_needed: false },
  { id: "sk-2026-07-21-migration-integration", title: "Beirat für Migration und Integration", starts_at: "2026-07-21T17:00:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Beirat", source: "sitzungskalender_2026", source_uid: "sk-2026-07-21-migration-integration", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Beirat für Migration und Integration", preparation_status: "offen", requires_preparation: true, decision_needed: false },
  { id: "sk-2026-07-27-ferienkommission", title: "Ferienkommission", starts_at: "2026-07-27T16:00:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Ferienkommission", source: "sitzungskalender_2026", source_uid: "sk-2026-07-27-ferienkommission", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Ferienkommission", preparation_status: "offen", requires_preparation: true, decision_needed: false },
  { id: "sk-2026-08-12-arbeitskreis-haushalt", title: "Arbeitskreis Haushalt", starts_at: "2026-08-12T16:00:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Arbeitskreis", source: "sitzungskalender_2026", source_uid: "sk-2026-08-12-arbeitskreis-haushalt", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Arbeitskreis Haushalt", preparation_status: "offen", requires_preparation: true, decision_needed: true },
  { id: "sk-2026-08-17-hufa", title: "Haupt- und Finanzausschuss", starts_at: "2026-08-17T15:00:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Ausschuss", source: "sitzungskalender_2026", source_uid: "sk-2026-08-17-hufa", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Haupt- und Finanzausschuss", preparation_status: "offen", requires_preparation: true, decision_needed: true },
  { id: "sk-2026-08-17-personalausschuss", title: "Personalausschuss", starts_at: "2026-08-17T16:00:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Ausschuss", source: "sitzungskalender_2026", source_uid: "sk-2026-08-17-personalausschuss", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Personalausschuss", preparation_status: "offen", requires_preparation: true, decision_needed: true },
  { id: "sk-2026-08-17-digitalisierungsausschuss", title: "Digitalisierungsausschuss", starts_at: "2026-08-17T16:30:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Ausschuss", source: "sitzungskalender_2026", source_uid: "sk-2026-08-17-digitalisierungsausschuss", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Digitalisierungsausschuss", preparation_status: "offen", requires_preparation: true, decision_needed: true },
  { id: "sk-2026-08-20-fraktionsvorsitzendenrunde", title: "Fraktionsvorsitzendenrunde", starts_at: "2026-08-20T18:00:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Fraktionsvorsitzendenrunde", source: "sitzungskalender_2026", source_uid: "sk-2026-08-20-fraktionsvorsitzendenrunde", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Fraktionsvorsitzendenrunde", preparation_status: "offen", requires_preparation: true, decision_needed: false },
  { id: "sk-2026-08-27-inklusionsbeirat", title: "Inklusionsbeirat", starts_at: "2026-08-27T17:00:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Beirat", source: "sitzungskalender_2026", source_uid: "sk-2026-08-27-inklusionsbeirat", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Inklusionsbeirat", preparation_status: "offen", requires_preparation: true, decision_needed: false },
  { id: "sk-2026-08-31-stadtrat", title: "Stadtrat", starts_at: "2026-08-31T15:00:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Stadtrat", source: "sitzungskalender_2026", source_uid: "sk-2026-08-31-stadtrat", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Stadtrat", preparation_status: "offen", requires_preparation: true, decision_needed: true },
  { id: "sk-2026-09-01-migration-integration", title: "Beirat für Migration und Integration", starts_at: "2026-09-01T17:00:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Beirat", source: "sitzungskalender_2026", source_uid: "sk-2026-09-01-migration-integration", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Beirat für Migration und Integration", preparation_status: "offen", requires_preparation: true, decision_needed: false },
  { id: "sk-2026-09-02-jugendhilfeausschuss", title: "Jugendhilfeausschuss", starts_at: "2026-09-02T15:00:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Ausschuss", source: "sitzungskalender_2026", source_uid: "sk-2026-09-02-jugendhilfeausschuss", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Jugendhilfeausschuss", preparation_status: "offen", requires_preparation: true, decision_needed: true },
  { id: "sk-2026-09-08-hufa-haushalt", title: "Haupt- und Finanzausschuss (Haushalt)", starts_at: "2026-09-08T15:00:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Ausschuss", source: "sitzungskalender_2026", source_uid: "sk-2026-09-08-hufa-haushalt", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Haupt- und Finanzausschuss", preparation_status: "offen", requires_preparation: true, decision_needed: true },
  { id: "sk-2026-09-09-hufa-haushalt", title: "Haupt- und Finanzausschuss (Haushalt)", starts_at: "2026-09-09T15:00:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Ausschuss", source: "sitzungskalender_2026", source_uid: "sk-2026-09-09-hufa-haushalt", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Haupt- und Finanzausschuss", preparation_status: "offen", requires_preparation: true, decision_needed: true },
  { id: "sk-2026-09-14-umweltausschuss", title: "Umweltausschuss", starts_at: "2026-09-14T15:00:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Ausschuss", source: "sitzungskalender_2026", source_uid: "sk-2026-09-14-umweltausschuss", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Umweltausschuss", preparation_status: "offen", requires_preparation: true, decision_needed: true },
  { id: "sk-2026-09-16-sportausschuss", title: "Sportausschuss", starts_at: "2026-09-16T16:00:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Ausschuss", source: "sitzungskalender_2026", source_uid: "sk-2026-09-16-sportausschuss", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Sportausschuss", preparation_status: "offen", requires_preparation: true, decision_needed: true },
  { id: "sk-2026-09-17-fraktionsvorsitzendenrunde", title: "Fraktionsvorsitzendenrunde", starts_at: "2026-09-17T18:00:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Fraktionsvorsitzendenrunde", source: "sitzungskalender_2026", source_uid: "sk-2026-09-17-fraktionsvorsitzendenrunde", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Fraktionsvorsitzendenrunde", preparation_status: "offen", requires_preparation: true, decision_needed: false },
  { id: "sk-2026-09-21-bauausschuss", title: "Bauausschuss", starts_at: "2026-09-21T15:00:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Ausschuss", source: "sitzungskalender_2026", source_uid: "sk-2026-09-21-bauausschuss", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Bauausschuss", preparation_status: "offen", requires_preparation: true, decision_needed: true },
  { id: "sk-2026-09-24-werkausschuss-stadtbildpflege", title: "Werkausschuss Stadtbildpflege", starts_at: "2026-09-24T14:30:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Ausschuss", source: "sitzungskalender_2026", source_uid: "sk-2026-09-24-werkausschuss-stadtbildpflege", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Werkausschuss Stadtbildpflege", preparation_status: "offen", requires_preparation: true, decision_needed: true },
  { id: "sk-2026-09-24-vr-stadtentwaesserung", title: "VR Stadtentwässerung", starts_at: "2026-09-24T15:30:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Ausschuss", source: "sitzungskalender_2026", source_uid: "sk-2026-09-24-vr-stadtentwaesserung", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "VR Stadtentwässerung", preparation_status: "offen", requires_preparation: true, decision_needed: true },
  { id: "sk-2026-09-28-stadtrat", title: "Stadtrat", starts_at: "2026-09-28T15:00:00+02:00", ends_at: null, all_day: false, location: null, description: null, category: "Stadtrat", source: "sitzungskalender_2026", source_uid: "sk-2026-09-28-stadtrat", owner: "Fraktion", relevance: "offen", status: "scheduled", meeting_body: "Stadtrat", preparation_status: "offen", requires_preparation: true, decision_needed: true }
];

export function mergeCalendarEvents(events: FraktionEvent[]) {
  const map = new Map<string, FraktionEvent>();
  [...sitzungskalender2026, ...events].forEach(event => {
    const key = event.source_uid || `${event.title}-${event.starts_at}`;
    map.set(key, event);
  });
  return Array.from(map.values()).sort((a, b) => new Date(a.starts_at).getTime() - new Date(b.starts_at).getTime());
}
